# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        echo "Running build commands"
      displayName: 'npm install and build'
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: dev-test
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                echo "Deployment done"
              displayName: 'Deploying to AWS'